[package]
name = "img_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
indicatif = "0.17.0"
structopt = "0.3.25"
clap = "3.0.0-beta.4"
imageproc = "0.23.0"
